name: E2E Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

        # 👇 Create Angular environment files for the build
      - name: Create environment files
        run: |
          set -e
          mkdir -p src/environments

          cat > src/environments/environment.ts <<EOF
          export const environment = {
            production: false,
            apiUrl: '/',
          };
          EOF

          cat > src/environments/environment.prod.ts <<EOF
          export const environment = {
            production: true,
            apiUrl: '${API_URL:-/}',
          };
          EOF

      - name: Build application
        run: npm run build

      - name: Run Playwright tests
        run: npm run test:e2e:stable

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
